#!/usr/bin/python3

import sys

command = ["scala", "-classpath", "visualizer/target/scala-3.1.2/amaranth.jar", "net.jmesyou.amaranth.Main"] + sys.argv[
                                                                                                               1:]
